// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYf4f_egHh_4Mr8j43maZlSglVGjaIAKc',
    appId: '1:29131849243:web:adbcca36f4fa627bfb02be',
    messagingSenderId: '29131849243',
    projectId: 'pebbles---habit-tracking',
    authDomain: 'pebbles---habit-tracking.firebaseapp.com',
    storageBucket: 'pebbles---habit-tracking.firebasestorage.app',
    measurementId: 'G-3Q13XK1KJ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlKqNzNaSXGqpGtTkJ8XeaemqcbMuGYfA',
    appId: '1:29131849243:android:c6f1c50e0f205a99fb02be',
    messagingSenderId: '29131849243',
    projectId: 'pebbles---habit-tracking',
    storageBucket: 'pebbles---habit-tracking.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDg_zQJrX6GzPuEo4YaByDbkiykAqrSMQE',
    appId: '1:29131849243:ios:ce758ada840ab221fb02be',
    messagingSenderId: '29131849243',
    projectId: 'pebbles---habit-tracking',
    storageBucket: 'pebbles---habit-tracking.firebasestorage.app',
    iosBundleId: 'com.example.pebblesHabitTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDg_zQJrX6GzPuEo4YaByDbkiykAqrSMQE',
    appId: '1:29131849243:ios:ce758ada840ab221fb02be',
    messagingSenderId: '29131849243',
    projectId: 'pebbles---habit-tracking',
    storageBucket: 'pebbles---habit-tracking.firebasestorage.app',
    iosBundleId: 'com.example.pebblesHabitTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDYf4f_egHh_4Mr8j43maZlSglVGjaIAKc',
    appId: '1:29131849243:web:8940a021d7b2dd3bfb02be',
    messagingSenderId: '29131849243',
    projectId: 'pebbles---habit-tracking',
    authDomain: 'pebbles---habit-tracking.firebaseapp.com',
    storageBucket: 'pebbles---habit-tracking.firebasestorage.app',
    measurementId: 'G-Y66844JJRZ',
  );
}
